import AVFoundation
import Accelerate
import CoreAudio
import Darwin
import SystemAudioRecorderRT
import Foundation

public struct CalibrationProfile: Codable, Sendable {
    public let deviceUID: String
    public let outputChannelCount: Int
    public let macOSBuild: String
    public let gainCompensationDB: Double
    public let measuredAt: String
    public let referenceVolume: Double?

    public init(deviceUID: String, outputChannelCount: Int, macOSBuild: String, gainCompensationDB: Double, measuredAt: String, referenceVolume: Double?) {
        self.deviceUID = deviceUID
        self.outputChannelCount = outputChannelCount
        self.macOSBuild = macOSBuild
        self.gainCompensationDB = gainCompensationDB
        self.measuredAt = measuredAt
        self.referenceVolume = referenceVolume
    }

    public var key: String { "\(deviceUID)|\(outputChannelCount)|\(macOSBuild)" }
}

public struct BufferCalibrationResult: Sendable {
    public let deviceUID: String
    public let deviceName: String
    public let selectedFrameSize: UInt32
    public let supportedFrameSizes: [UInt32]
    public let rejectedFrameSizes: [UInt32]
}

/// A persisted `recommendBufferFrameSize` result for one device, keyed by
/// `deviceUID` only — unlike `CalibrationProfile`'s gain compensation, the
/// hardware's true buffer-size floor doesn't depend on output channel count
/// or macOS build.
public struct BufferSizeCalibration: Codable, Sendable {
    public let deviceUID: String
    public let frameSize: UInt32
    public let measuredAt: String

    public init(deviceUID: String, frameSize: UInt32, measuredAt: String) {
        self.deviceUID = deviceUID
        self.frameSize = frameSize
        self.measuredAt = measuredAt
    }
}

/// Bug-A calibration (Section 8.3): with user consent, plays a 997 Hz test
/// tone through the target device while capturing via a temporary lane,
/// measures the RMS delta, and stores a per-device gain profile. Playback
/// uses AVFoundation (Section 2.2 — playback side only, never capture);
/// capture uses a normal `CaptureLane`-equivalent temporary tap.
public enum CalibrationService {
    private static let toneFrequency: Double = 997
    private static let toneDurationSeconds: Double = 5
    private static let toneLevelDBFS: Double = -20
    private static let measurementWindowStartSeconds: Double = 1 // skip first 1s (ramp/settling)
    private static let measurementWindowEndSeconds: Double = 4   // skip last 1s

    /// Fallback ladder used only if the device's real
    /// `kAudioDevicePropertyBufferFrameSizeRange` can't be read.
    public static let bufferFrameSizeCandidates: [UInt32] = [128, 256, 512, 1024, 2048, 4096]

    /// Power-of-two rungs tried above the hardware's reported floor.
    private static let bufferFrameSizeLadder: [UInt32] = [16, 32, 64, 128, 256, 512, 1024, 2048, 4096]

    /// Candidates to probe, floor first: the device's true minimum — the
    /// absolute bound below which the hardware physically cannot go, i.e.
    /// the best possible latency this system could ever offer — followed by
    /// ascending rungs up to `maximum` (the hardware's own reported
    /// ceiling). Rungs come from the power-of-two ladder where it still
    /// applies; if `minimum` is already at or past the ladder's top, rungs
    /// are generated by doubling instead, so an unusually high hardware
    /// floor still gets fallback candidates rather than collapsing to one
    /// untested value.
    static func candidateFrameSizes(deviceMinimum minimum: UInt32, maximum: UInt32) -> [UInt32] {
        var candidates: [UInt32] = [minimum]
        guard maximum > minimum else { return candidates }

        var rung = bufferFrameSizeLadder.first { $0 > minimum } ?? minimum
        while rung <= minimum {
            let (doubled, overflowed) = rung.multipliedReportingOverflow(by: 2)
            if overflowed { return candidates }
            rung = doubled
        }
        while rung <= maximum {
            candidates.append(rung)
            let (doubled, overflowed) = rung.multipliedReportingOverflow(by: 2)
            if overflowed { break }
            rung = doubled
        }
        return candidates
    }

    /// Profiles persist as shared JSON at `~/Library/Application Support/
    /// System Audio Recorder/calibration.json` (Section 8.3), read/written by
    /// both the GUI and the CLI (separate processes, no IPC), written atomically.
    public static var profileStoreURL: URL {
        let appSupport = FileManager.default.urls(for: .applicationSupportDirectory, in: .userDomainMask)[0]
        return appSupport.appendingPathComponent("System Audio Recorder").appendingPathComponent("calibration.json")
    }

    public static func loadProfiles() -> [CalibrationProfile] {
        guard let data = try? Data(contentsOf: profileStoreURL) else { return [] }
        return (try? JSONDecoder().decode([CalibrationProfile].self, from: data)) ?? []
    }

    public static func saveProfile(_ profile: CalibrationProfile) {
        let dir = profileStoreURL.deletingLastPathComponent()
        try? FileManager.default.createDirectory(at: dir, withIntermediateDirectories: true)

        // The GUI and CLI are separate OS processes with no shared memory,
        // so an in-process lock (NSLock, DispatchQueue) cannot stop one
        // process's write from clobbering a concurrent update from the
        // other — the atomic tmp+rename below only makes each individual
        // WRITE torn-free, not the read-modify-write sequence as a whole.
        // `flock` on a dedicated lock file serializes that whole sequence
        // across processes.
        let lockURL = dir.appendingPathComponent("calibration.json.lock")
        let lockFD = open(lockURL.path, O_CREAT | O_RDWR, 0o644)
        guard lockFD >= 0 else {
            // Can't acquire the coordination mechanism at all — fall back
            // to an unsynchronized save rather than losing this profile.
            saveProfileUnlocked(profile, dir: dir)
            return
        }
        defer { close(lockFD) }
        flock(lockFD, LOCK_EX)
        defer { flock(lockFD, LOCK_UN) }

        saveProfileUnlocked(profile, dir: dir)
    }

    private static func saveProfileUnlocked(_ profile: CalibrationProfile, dir: URL) {
        var profiles = loadProfiles()
        profiles.removeAll { $0.key == profile.key }
        profiles.append(profile)
        guard let data = try? JSONEncoder().encode(profiles) else { return }
        let tmp = dir.appendingPathComponent("calibration.json.tmp")
        try? data.write(to: tmp, options: .atomic)
        _ = try? FileManager.default.replaceItemAt(profileStoreURL, withItemAt: tmp)
    }

    public static func profile(deviceUID: String, outputChannelCount: Int, macOSBuild: String) -> CalibrationProfile? {
        let key = "\(deviceUID)|\(outputChannelCount)|\(macOSBuild)"
        return loadProfiles().first { $0.key == key }
    }

    /// Sibling of `profileStoreURL`, same shared-JSON-file rationale — the
    /// buffer-size floor `recommendBufferFrameSize` measures must be visible
    /// to the CLI's `record`, which runs in a separate process with its own
    /// `UserDefaults` domain and so can never see the GUI's `AppStorage`.
    public static var bufferCalibrationStoreURL: URL {
        profileStoreURL.deletingLastPathComponent().appendingPathComponent("buffer-calibration.json")
    }

    public static func loadBufferSizeCalibrations() -> [BufferSizeCalibration] {
        guard let data = try? Data(contentsOf: bufferCalibrationStoreURL) else { return [] }
        return (try? JSONDecoder().decode([BufferSizeCalibration].self, from: data)) ?? []
    }

    public static func saveBufferSizeCalibration(_ calibration: BufferSizeCalibration) {
        let dir = bufferCalibrationStoreURL.deletingLastPathComponent()
        try? FileManager.default.createDirectory(at: dir, withIntermediateDirectories: true)

        // Same cross-process race as saveProfile() above — a dedicated lock
        // file (distinct from calibration.json.lock: an unrelated gain-
        // profile write must not block a buffer-size write or vice versa).
        let lockURL = dir.appendingPathComponent("buffer-calibration.json.lock")
        let lockFD = open(lockURL.path, O_CREAT | O_RDWR, 0o644)
        guard lockFD >= 0 else {
            saveBufferSizeCalibrationUnlocked(calibration, dir: dir)
            return
        }
        defer { close(lockFD) }
        flock(lockFD, LOCK_EX)
        defer { flock(lockFD, LOCK_UN) }

        saveBufferSizeCalibrationUnlocked(calibration, dir: dir)
    }

    private static func saveBufferSizeCalibrationUnlocked(_ calibration: BufferSizeCalibration, dir: URL) {
        var calibrations = loadBufferSizeCalibrations()
        calibrations.removeAll { $0.deviceUID == calibration.deviceUID }
        calibrations.append(calibration)
        guard let data = try? JSONEncoder().encode(calibrations) else { return }
        let tmp = dir.appendingPathComponent("buffer-calibration.json.tmp")
        try? data.write(to: tmp, options: .atomic)
        _ = try? FileManager.default.replaceItemAt(bufferCalibrationStoreURL, withItemAt: tmp)
    }

    public static func calibratedBufferFrameSize(deviceUID: String) -> UInt32? {
        loadBufferSizeCalibrations().first { $0.deviceUID == deviceUID }?.frameSize
    }

    /// Resolves the buffer size a session should start with: the shared
    /// calibration for `deviceID` if one exists, else 512. `deviceID` is the
    /// caller's own already-resolved device (`AudioDeviceDirectory.resolveDevice`)
    /// — this never re-resolves the `DevicePolicy` itself, so a caller that
    /// also needs the device for other reasons (e.g. `TapFactory.create`)
    /// only pays that HAL round trip once per build/rebuild.
    public static func effectiveBufferFrameSize(forResolvedDevice deviceID: AudioObjectID) -> UInt32 {
        guard let deviceUID = try? AudioDeviceDirectory.deviceUID(deviceID),
              let frameSize = calibratedBufferFrameSize(deviceUID: deviceUID) else {
            return 512
        }
        return frameSize
    }

    /// Finds the lowest I/O buffer size this system can apply to the app's
    /// actual tap + private aggregate path and start successfully.
    public static func recommendBufferFrameSize(
        engineQueue: DispatchQueue,
        completion: @escaping (Result<BufferCalibrationResult, Error>) -> Void
    ) {
        engineQueue.async {
            do {
                guard PermissionBroker.requestCapturePermission() == .granted else {
                    throw CalibrationError.permissionDenied
                }

                let deviceID = try AudioDeviceDirectory.defaultOutputDevice()
                let deviceUID = try AudioDeviceDirectory.deviceUID(deviceID)
                let deviceName = (try? AudioDeviceDirectory.deviceName(deviceID)) ?? "Default Output"

                let candidates: [UInt32]
                if let hardwareRange = try? AudioDeviceDirectory.bufferFrameSizeRange(deviceID) {
                    candidates = candidateFrameSizes(
                        deviceMinimum: hardwareRange.lowerBound,
                        maximum: hardwareRange.upperBound
                    )
                } else {
                    candidates = bufferFrameSizeCandidates
                }

                var supported: [UInt32] = []
                var rejected: [UInt32] = []
                for frameSize in candidates {
                    if canStartTemporaryCapture(deviceUID: deviceUID, bufferFrameSize: frameSize) {
                        supported.append(frameSize)
                    } else {
                        rejected.append(frameSize)
                    }
                }

                guard let selected = supported.first else {
                    throw CalibrationError.noSupportedBufferFrameSize
                }

                saveBufferSizeCalibration(BufferSizeCalibration(
                    deviceUID: deviceUID, frameSize: selected, measuredAt: ManifestTimestamp.now()
                ))

                completion(.success(BufferCalibrationResult(
                    deviceUID: deviceUID,
                    deviceName: deviceName,
                    selectedFrameSize: selected,
                    supportedFrameSizes: supported,
                    rejectedFrameSizes: rejected
                )))
            } catch {
                completion(.failure(error))
            }
        }
    }

    /// Runs the full calibration pass end to end. `engineQueue` is the
    /// caller's `CaptureEngine` engine queue (a temporary tap must still obey
    /// the Section 4.4 serialization rule). Completion is called with the
    /// measured `gainCompensationDB`, or an error.
    public static func runCalibration(
        deviceUID: String,
        engineQueue: DispatchQueue,
        completion: @escaping (Result<CalibrationProfile, Error>) -> Void
    ) {
        engineQueue.async {
            do {
                guard let deviceID = try AudioDeviceDirectory.findDevice(byUID: deviceUID) else {
                    throw CalibrationError.deviceNotFound
                }
                let channelCount = try AudioDeviceDirectory.outputChannelCount(deviceID)

                let capturedRMSdB = try captureToneAndMeasure(deviceID: deviceID, deviceUID: deviceUID)
                let gainCompensationDB = toneLevelDBFS - capturedRMSdB

                let macOSBuild = ProcessInfo.processInfo.operatingSystemVersionString
                let profile = CalibrationProfile(
                    deviceUID: deviceUID,
                    outputChannelCount: channelCount,
                    macOSBuild: macOSBuild,
                    gainCompensationDB: gainCompensationDB,
                    measuredAt: ManifestTimestamp.now(),
                    referenceVolume: nil // Section 11 R1: pre/post-volume question needs hands-on verification
                )
                saveProfile(profile)
                completion(.success(profile))
            } catch {
                completion(.failure(error))
            }
        }
    }

    /// Plays the test tone via AVAudioPlayer while capturing through a
    /// temporary tap+aggregate (built directly with TapFactory, bypassing
    /// CaptureLane's full session/manifest machinery since this is a
    /// throwaway measurement, not a recording).
    private static func captureToneAndMeasure(deviceID: AudioObjectID, deviceUID: String) throws -> Double {
        let toneURL = try generateToneFile()
        defer { try? FileManager.default.removeItem(at: toneURL) }

        let spec = SessionSpec(device: .fixed(deviceUID: deviceUID))
        let handle = try TapFactory.create(
            spec: spec, laneSlug: "calibration", excludeProcessIDs: [], bufferFrameSize: 512
        )
        defer { TapFactory.destroy(handle) }

        let channels = Int(handle.effectiveFormat.mChannelsPerFrame)
        let bytesPerFrame = UInt32(4 * channels)
        let ringBytes = Int(handle.effectiveFormat.mSampleRate) * channels * 4 * 8
        guard let ring = td_ring_create(ringBytes) else { throw CalibrationError.allocationFailed }
        defer { td_ring_destroy(ring) }
        guard let ctx = td_context_create(ring, bytesPerFrame) else { throw CalibrationError.allocationFailed }
        defer { td_context_destroy(ctx) }
        td_context_arm_first_host_time(ctx)

        let isInterleaved = (handle.effectiveFormat.mFormatFlags & kAudioFormatFlagIsNonInterleaved) == 0
        // IOProcHost's init already registers the IOProc with Core Audio —
        // the defer must be in place BEFORE `host.start()` can throw, or a
        // failed start() leaks that registration forever (a `defer`
        // written after a throwing call is never reached, and thus never
        // scheduled, if that call throws).
        let host = try IOProcHost(aggregateID: handle.aggregateID, context: ctx, interleaved: isInterleaved)
        defer { host.stop(); host.destroyIOProc() }
        try host.start()

        let player = try AVAudioPlayer(contentsOf: toneURL)
        player.play()

        var accumulatedSumSquares: Double = 0
        var accumulatedSampleCount: Int = 0
        let scratchFrames = 48000
        var scratch = [UInt8](repeating: 0, count: scratchFrames * Int(bytesPerFrame))

        let deadline = Date().addingTimeInterval(toneDurationSeconds + 1.5)
        while Date() < deadline {
            Thread.sleep(forTimeInterval: 0.1)
            let elapsed = toneDurationSeconds + 1.5 - deadline.timeIntervalSinceNow
            let inMeasurementWindow = elapsed >= measurementWindowStartSeconds && elapsed <= measurementWindowEndSeconds

            let bytesRead = scratch.withUnsafeMutableBytes { raw -> Int in
                td_ring_read(ring, raw.baseAddress, raw.count, bytesPerFrame)
            }
            guard inMeasurementWindow, bytesRead > 0 else { continue }

            scratch.withUnsafeBytes { raw in
                let floatCount = bytesRead / 4
                let floatPtr = raw.baseAddress!.assumingMemoryBound(to: Float.self)
                var meanSquare: Float = 0
                vDSP_measqv(floatPtr, 1, &meanSquare, vDSP_Length(floatCount))
                accumulatedSumSquares += Double(meanSquare) * Double(floatCount)
                accumulatedSampleCount += floatCount
            }
        }
        player.stop()

        guard accumulatedSampleCount > 0 else { throw CalibrationError.noSamplesCaptured }
        let meanSquare = accumulatedSumSquares / Double(accumulatedSampleCount)
        let rms = sqrt(meanSquare)
        guard rms > 0 else { throw CalibrationError.silentCapture }
        return 20 * log10(rms)
    }

    private static func canStartTemporaryCapture(deviceUID: String, bufferFrameSize: UInt32) -> Bool {
        let ownPID = ProcessInfo.processInfo.processIdentifier
        let ownProcessObjectID = try? ProcessCatalog.translatePIDToProcessObject(ownPID)
        let excludeList: [AudioObjectID] = ownProcessObjectID.map { [$0] } ?? []

        var handle: TapHandle?
        var host: IOProcHost?
        var ring: OpaquePointer?
        var ctx: OpaquePointer?

        defer {
            host?.stop()
            host?.destroyIOProc()
            if let handle {
                TapFactory.destroy(handle)
            }
            if let ctx {
                td_context_destroy(ctx)
            }
            if let ring {
                td_ring_destroy(ring)
            }
        }

        do {
            let spec = SessionSpec(device: .fixed(deviceUID: deviceUID))
            let createdHandle = try TapFactory.create(
                spec: spec,
                laneSlug: "buffer-calibration-\(bufferFrameSize)",
                excludeProcessIDs: excludeList,
                bufferFrameSize: bufferFrameSize
            )
            handle = createdHandle

            let channels = Int(createdHandle.effectiveFormat.mChannelsPerFrame)
            let bytesPerFrame = UInt32(4 * channels)
            let ringBytes = max(Int(createdHandle.effectiveFormat.mSampleRate) * channels * 4, Int(bytesPerFrame))
            guard let createdRing = td_ring_create(ringBytes) else { return false }
            ring = createdRing
            guard let createdContext = td_context_create(createdRing, bytesPerFrame) else { return false }
            ctx = createdContext
            td_context_arm_first_host_time(createdContext)

            let isInterleaved = (createdHandle.effectiveFormat.mFormatFlags & kAudioFormatFlagIsNonInterleaved) == 0
            let createdHost = try IOProcHost(
                aggregateID: createdHandle.aggregateID,
                context: createdContext,
                interleaved: isInterleaved
            )
            host = createdHost
            try createdHost.start()
            Thread.sleep(forTimeInterval: 0.15)
            return true
        } catch {
            return false
        }
    }

    /// Generates a 5 s, -20 dBFS, 997 Hz sine as a temporary AIFF file for
    /// AVAudioPlayer playback.
    private static func generateToneFile() throws -> URL {
        let sampleRate: Double = 48000
        let frameCount = Int(sampleRate * toneDurationSeconds)
        let amplitude = Float(pow(10.0, toneLevelDBFS / 20.0))

        var asbd = AudioStreamBasicDescription(
            mSampleRate: sampleRate, mFormatID: kAudioFormatLinearPCM,
            mFormatFlags: kAudioFormatFlagIsFloat | kAudioFormatFlagIsPacked,
            mBytesPerPacket: 8, mFramesPerPacket: 1, mBytesPerFrame: 8,
            mChannelsPerFrame: 2, mBitsPerChannel: 32, mReserved: 0
        )
        let url = FileManager.default.temporaryDirectory.appendingPathComponent("systemaudiorecorder_calibration_tone_\(UUID().uuidString).aiff")
        var file: ExtAudioFileRef?
        guard ExtAudioFileCreateWithURL(url as CFURL, kAudioFileAIFFType, &asbd, nil, AudioFileFlags.eraseFile.rawValue, &file) == noErr,
              let f = file else {
            throw CalibrationError.toneGenerationFailed
        }
        // From here on, `url` already exists on disk (ExtAudioFileCreateWithURL
        // created it) — every failure exit must remove it, or a temp AIFF
        // is left behind in ~/tmp for every failed calibration attempt.
        var clientASBD = asbd
        guard ExtAudioFileSetProperty(f, kExtAudioFileProperty_ClientDataFormat, UInt32(MemoryLayout<AudioStreamBasicDescription>.size), &clientASBD) == noErr else {
            ExtAudioFileDispose(f)
            try? FileManager.default.removeItem(at: url)
            throw CalibrationError.toneGenerationFailed
        }

        var samples = [Float32](repeating: 0, count: frameCount * 2)
        for i in 0..<frameCount {
            let t = Double(i) / sampleRate
            let v = amplitude * Float(sin(2 * Double.pi * toneFrequency * t))
            samples[i * 2] = v
            samples[i * 2 + 1] = v
        }
        let writeStatus = samples.withUnsafeMutableBytes { raw -> OSStatus in
            var bl = AudioBufferList(mNumberBuffers: 1, mBuffers: AudioBuffer(mNumberChannels: 2, mDataByteSize: UInt32(raw.count), mData: raw.baseAddress))
            return ExtAudioFileWrite(f, UInt32(frameCount), &bl)
        }
        ExtAudioFileDispose(f)
        guard writeStatus == noErr else {
            try? FileManager.default.removeItem(at: url)
            throw CalibrationError.toneGenerationFailed
        }
        return url
    }
}

public enum CalibrationError: Error, CustomStringConvertible {
    case deviceNotFound
    case permissionDenied
    case allocationFailed
    case noSamplesCaptured
    case noSupportedBufferFrameSize
    case silentCapture
    case toneGenerationFailed

    public var description: String {
        switch self {
        case .deviceNotFound: return "Calibration device not found"
        case .permissionDenied: return "System audio capture permission was not granted"
        case .allocationFailed: return "Failed to allocate ring/context for calibration"
        case .noSamplesCaptured: return "No samples captured during calibration window"
        case .noSupportedBufferFrameSize: return "No supported I/O buffer size could be started"
        case .silentCapture: return "Captured signal was silent — check device volume/routing"
        case .toneGenerationFailed: return "Failed to generate calibration tone file"
        }
    }
}
